// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxkcwvzfdmxzmzeymchm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4a2N3dnpmZG14em16ZXltY2htIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMTQ5MjUsImV4cCI6MjA3Mzg5MDkyNX0.rBQNmcWfSgEd9-SOVZEw78APJBz-Qzlj4hGYCh0E3dI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});